my_app/urls.py
from django.urls import path
# from . import views
from . import views
from .views import AddFormView,CarView,ListView,DetailView,CarUpdate,CarDelete

app_name = 'my_app'

urlpatterns = [

    path('',views.simple_view,name='index'),
    path('variable',views.variable,name='variable'),
    path('list',views.list,name='list'),
    path('add',views.add,name='add'),
    path('delete',views.delete,name='delete'),
    path('cadd',AddFormView.as_view(),name='cadd'),
    path('aadd',CarView.as_view(),name='aadd'),
    path('c_list',ListView.as_view(),name='c_list'),
     path('car_detail/<int:pk>',DetailView.as_view(),name='dd'),
    path('car_update/<int:pk>',CarUpdate.as_view(),name='up'),  
      path('car_delete/<int:pk>',CarDelete.as_view(),name='dd'),  
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from . import views

urlpatterns =   [
    path('my_app/',include('my_app.urls')),
    path("admin/", admin.site.urls),
    path("", views.home_view),
     path('catalog/',include('catalog.urls')),
        path("accounts/", include('django.contrib.auth.urls')),
          
    #    path('',RedirectView.as_view(url="catalog")),
]

my_app/models.py
from django.db import models

# Create your models here.
class Patient(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()


class Car(models.Model):
    brand = models.CharField(max_length=20)
    year = models.IntegerField()


    def __str__(self):
        return f"Car brand is {self.brand} {self.year} "
    

my_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Car


class CarForm(forms.Form):
    brand = forms.CharField(label='Brand Name')
    year = forms.IntegerField(label='Year')


# class CarForm(ModelForm):
#     class Meta:
#         model = Car
#         fields = "__all__"

my_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseNotFound,Http404,HttpResponseRedirect
from . import models
from django.urls import reverse,reverse_lazy
from .forms import CarForm
from django.contrib import messages
from django.views.generic import TemplateView,FormView,CreateView,ListView,DetailView,UpdateView,DeleteView
from my_app.models import Car
articles ={
    'sport':'sport page',
    'finance':'finance page',
   'politics':'politics page',
}



def simple_view(request):
    my_var = {'first_name':'Eniola','last_name':'Ajani','some_list':[1,2,4] ,'status':True}
    return render(request,'my_app/example.html',context=my_var) #

def variable(request):
     return render(request,'my_app/variable.html') #
def list_user(request):
    all_users = models.Patient.objects.all()
    users = {'uses':all_users}
    print(all_users);
    print("all_users");
    return render(request,'my_app/list.html',context=users) #
 


def list(request):
    all_cars = models.Car.objects.all()
    cars = {'cars':all_cars}
    return render(request,'my_app/list.html',context=cars) #


def add(request):
    if request.POST:
        # brand = request.POST['brand']
        # year = int(request.POST['year'])
        form = CarForm(request.POST)
        if form.is_valid():
            
            form.save()
            messages.success(request, 'created ')
            return redirect(reverse('my_app:list'))
    else:
        form = CarForm()
  
        return render(request,'my_app/add.html',context={"forms":form}) #

def delete(request):
    if request.POST:
        pk = request.POST['pk']
        models.Car.objects.get(pk=pk).delete()
        return redirect(reverse('my_app:list'))
    else:
        return render(request,'my_app/delete.html') #
    




class HomeView(TemplateView):
    
    template_name = 'my_app/example.html'


class AddFormView(FormView):
     form_class= CarForm
     template_name = 'my_app/add.html'

     success_url = reverse_lazy("my_app:list")

     def form_valid(self, form):
         
       if form.is_valid():
            
            print(form.cleaned_data)
         
            return super().form_valid(form)
     
     def get(self, request, **kwargs):
        context = self.get_context_data()
        print(context['view'])
        
        # Add additional logic, maybe htmx or something else.
        
        return render(request, self.template_name, context={"forms":context['form']})
     


class CarView(CreateView):
    model = Car
    fields = "__all__"
    success_url = reverse_lazy("my_app:list")

class ListView(ListView):
    model = Car
    queryset = Car.objects.order_by('year')

class DetailView(DetailView):
    model = Car


class CarUpdate(UpdateView):
    model = Car
    fields = ['brand','year']
    success_url = reverse_lazy("my_app:list")

class CarDelete(DeleteView):
    model = Car

    success_url = reverse_lazy("my_app:c_list")

my_app/templates/my_app/add.html
{% extends "base.html" %}


{% block  content %}

<div class="container mt-5 myform">
    <h1 class="text-center mb-4">Brand and Year Form</h1>
    <form  method="post" >
        {% csrf_token %}


{% for  field in forms   %}
{{field.label_tag}}
<div class="form-control">
    {{field}}
</div>


{% endfor %}

        {% comment %} <div class="mb-3">
            <label for="brand" class="form-label">Brand:</label>
            <input type="text" id="brand" name="brand" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="year" class="form-label">Year:</label>
            <input type="number" id="year" name="year" class="form-control" min="1900" max="2099" required>
        </div> {% endcomment %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>


 

    {% endblock  %}

my_app/templates/my_app/car_confirm_delete.html
<h2>{{car}}</h2>


<div class="container mt-5 myform">
    <h1 class="text-center mb-4"> Delete Car </h1>
    <form  method="post" >
        {% csrf_token %}


<button type="submit" class="btn btn-danger">Delete</button>
</form>

my_app/templates/my_app/car_detail.html
{{car}}

my_app/templates/my_app/car_form.html
{% extends "base.html" %}


{% block  content %}

<div class="container mt-5 myform">
    <h1 class="text-center mb-4">Car </h1>
    <form  method="post" >
        {% csrf_token %}
{{form.as_p}}

<button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock  %}

my_app/templates/my_app/car_list.html
{% extends "base.html" %}


{% block  content %}
<h1>List All CarsView</h1>

{% if object_list  %}
<ul>
    {% for car  in object_list  %}

        <p> The Car brand is {{car.brand}} and make is {{car.year}} {{car.id}} <a href="car_detail/{{car.id}}">More</a><a href="car_update/{{car.id}}">update</a> <a href="car_delete/{{car.id}}">remove</a>  </p>

    {% endfor %}


</ul>

{% else %}

    <p>No record found </p>
{% endif %}
 

    {% endblock  %}

my_app/templates/my_app/delete.html
{% extends "base.html" %}


{% block  content %}


<div class="container mt-5">
    <h1 class="text-center mb-4">Remove Brand</h1>
    <form action="" method="post" class="shadow p-4 rounded bg-light">
        {% csrf_token %}
        <div class="mb-3">
            <label for="brand" class="form-label">PK Number:</label>
            <input type="text" id="pk" name="pk" class="form-control" required>
        </div>
   
        <button type="submit" class="btn btn-danger">Remove</button>
    </form>
</div>


 

    {% endblock  %}

my_app/templates/my_app/example.html
{% extends "base.html" %}


{% block  content %}


<h1>EXAMPLE HTML</h1>

<h4>{{first_name| upper}}</h4>
<h4>{{last_name}}</h4>

{% if last_name == 'Ajani'  %}
        {{first_name}}

{% else  %} 
        {{first_name}}

{% endif  %}

<ul>
{% for x in some_list %}

<h3>{{x}}</h3>

{% endfor %}


</ul>

<a href="{% url 'my_app:variable' %}">click to navigate</a>

{% endblock  %}

my_app/templates/my_app/list.html
{% extends "base.html" %}


{% block  content %}
<h1>List All Cars</h1>

{% if cars  %}
<ul>
    {% for car  in cars  %}

        <p> The Car brand is {{car.brand}} and make is {{car.year}} </p>

    {% endfor %}


</ul>

{% else %}

    <p>No record found </p>
{% endif %}
 

    {% endblock  %}

my_app/templates/my_app/variable.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    ddd
</body>
</html>