catalog/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_view,ModelCreateView,ModelDetailView,ModelDetailView,ModelDeleteView,CreateUserView
app_name = 'catalog'
urlpatterns =   [
  
    path("", home_view ,name='index'),
    path("book_create", ModelCreateView.as_view() ,name='book_create'),
    path("book_detail/<int:pk>", ModelDetailView.as_view() ,name='book_detail'),
    path("book_delete/<int:pk>", ModelDeleteView.as_view() ,name='book_delete'),
     path("signup/", CreateUserView.as_view(),name="signup"),
 
]

my_app/urls.py
from django.urls import path
# from . import views
from . import views
from .views import AddFormView,CarView,ListView,DetailView,CarUpdate,CarDelete

app_name = 'my_app'

urlpatterns = [

    path('',views.simple_view,name='index'),
    path('variable',views.variable,name='variable'),
    path('list',views.list,name='list'),
    path('add',views.add,name='add'),
    path('delete',views.delete,name='delete'),
    path('cadd',AddFormView.as_view(),name='cadd'),
    path('aadd',CarView.as_view(),name='aadd'),
    path('c_list',ListView.as_view(),name='c_list'),
     path('car_detail/<int:pk>',DetailView.as_view(),name='dd'),
    path('car_update/<int:pk>',CarUpdate.as_view(),name='up'),  
      path('car_delete/<int:pk>',CarDelete.as_view(),name='dd'),  
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from . import views

urlpatterns =   [
    path('my_app/',include('my_app.urls')),
    path("admin/", admin.site.urls),
    path("", views.home_view),
     path('catalog/',include('catalog.urls')),
        path("accounts/", include('django.contrib.auth.urls')),
          
    #    path('',RedirectView.as_view(url="catalog")),
]

templates/base.html
{% comment %} <html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% load static %}
<img src="{%  static 'my_app/DSC_1715.jpg' %}" alt="img" />
   
{% block content  %}
{% endblock  %}

<footer>
    footer
</footer>
</body>
</html> {% endcomment %}


{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <link rel="stylesheet" href="{% static 'my_app/customs.css' %}" >

</head>
<body>
    {% comment %} <img src="{%  static 'my_app/DSC_1715.jpg' %}" alt="img" /> {% endcomment %}
<div class="container mt-5">

  {% if user.is_authenticated %}

      <p>welcome:{{user.get_username}} <a href ="{% url 'logout' %}?next={{request.path}}">Logout</a> </p>
      <ul class="nav bg-info">
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'my_app:add' %}">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'my_app:c_list' %}">MEMBERS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'catalog:index' %}">Catalog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'catalog:book_create' %}">Create Books</a>
        </li>
      </ul>
  
      {% block content %}
      {% endblock %}
  {% else %}
  <p>You are not logged in <a href ="{% url 'login' %}?next={{request.path}}">Login</a>  </p>

  {% endif %}


</div>
</body>
</html>